#!/bin/sh -e
# This builds a full set of modules and updates the system modules profile with the result.
nix-env -p $NIX_STATE_DIR/profiles/system/modules -i -f `dirname $0` -A modules
nix-env -p $NIX_STATE_DIR/profiles/system/jupyter -i -f `dirname $0` -A jupyter-env
nix-env -p $NIX_STATE_DIR/profiles/system/nix -i -f `dirname $0` -A nix

moddir=/cm/shared/sw/modules/modules-nix
rm -f $moddir/*
for p in $NIX_STATE_DIR/profiles/system/modules-*-link ; do
	t=$(stat -c %Y $p)
	b=${p#*/modules-}
	cat <<EOF > $moddir/$(date -d @$t +%Y%m%d)-${b%-link}
#%Module1.0#
module-whatis "Show bleeding-edge modules based on nix build from $(date -d @$t)"
prepend-path MODULEPATH $p/modules
EOF
done
