source $stdenv/setup

shopt -s nullglob

modfile="$out/modules/$modName"
mkdir -p `dirname "$modfile"`

root=$buildInputs
cat > $modfile <<EOF
#%Module1.0#####################################################################
#
# Autogenerated nix $module
# 

set pkg $pkgName
set version $pkgVersion
set root $root

proc ModulesHelp { } {
    puts stderr "Sets the environment for nix-built \$pkg-\$version"
    puts stderr "Autogenerated for nix package $root"
}

module-whatis   "Sets the environment for nix-built \$pkg-\$version"

EOF

if [[ $modLoad ]] ; then
	echo "module load $modLoad" >> $modfile
	echo "prereq $modLoad" >> $modfile
fi
if [[ $modPrereq ]] ; then
	echo "prereq $modPrereq" >> $modfile
fi
if [[ $modConflict ]] ; then
	echo "conflict $modConflict" >> $modfile
fi

declare -A done
addPaths () {
	if [[ ${done[$1]} ]] ; then
		return
	fi
	done[$1]=1

	if [[ -e $1/nix-support/propagated-user-env-packages ]] ; then
		for p in `< $1/nix-support/propagated-user-env-packages` ; do
			addPaths $p
		done
	fi

	if [[ -d $1/bin ]] ; then
		echo "prepend-path PATH $1/bin" >> $modfile
	fi
	if [[ -d $1/share/man ]] ; then
		echo "prepend-path MANPATH $1/share/man" >> $modfile
	fi
	if [[ -d $1/lib/pkgconfig ]] ; then
		echo "prepend-path PKG_CONFIG_PATH $1/lib/pkgconfig" >> $modfile
	fi
	if [[ -d $1/share/pkgconfig ]] ; then
		echo "prepend-path PKG_CONFIG_PATH $1/share/pkgconfig" >> $modfile
	fi
	if [[ -d $1/lib/perl5/site_perl ]] ; then
		echo "prepend-path PERL5LIB $1/lib/perl5/site_perl" >> $modfile
	fi
	libs=($1/lib/lib*.so)
	if [[ $addLDLibraryPath && -n $libs ]] ; then
		echo "prepend-path LD_LIBRARY_PATH $1/lib" >> $modfile
	fi
	if [[ $addCFlags && ( -d $1/include || -n $libs ) ]] ; then
		if [[ -z $gccPrereq ]] ; then
			echo "prereq ${modPrefix}gcc" >> $modfile
			gccPrereq=1
		fi
		if [[ -d $1/include ]] ; then
			# nix uses -isystem but we'll just use -I
			echo "prepend-path -d \" \" NIX_${nixInfix}_CFLAGS_COMPILE -I$1/include" >> $modfile
		fi
		if [[ -n $libs ]] ; then
			echo "prepend-path -d \" \" NIX_${nixInfix}_LDFLAGS -L$1/lib" >> $modfile
		fi
	fi
}

addPaths $root
